spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDb?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: salman
    password: salmanqwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

